name: vue-assetfindr
services:
  nginx:
    type: nginx
    webroot: .output/public
  node:
    type: node:18
    ports:
      - 3000:3000
    run:
      - npm install
      - npm run generate
tooling:
  npm:
    service: node
  node:
    service: node
proxy:
  nginx:
    - vue-assetfindr.lndo.site
